### ISSUE TITLE
Detailed System Architecture Diagram

### ISSUE THREAD

**Issue by Dar13** [Dar13/OpenMemDB#4]
Each major module must have a detailed architecture diagram as part of Milestone 1.

Each maintainer is responsible for their respective modules.

**Comment by Dar13** [comment]
WorkManager diagrams have been created and uploaded to Google Drive.

**Comment by mjm07r** [comment]
libmem class and sequence diagrams have been uploaded to Google Drive

**Comment by Dar13** [comment]
Disk Synchronization activity diagram has been created and has been uploaded to Google Drive.

**Comment by Dar13** [comment]
All system components have architecture diagrams. Closing this issue to finish out Milestone 1.
